name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Compile application
        run: |
          ./mvnw clean package

      - name: Build Docker image
        run: |
          docker build -t jordyhenman/henman-wopro-service .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u jordyhenman --password-stdin

      - name: Push Docker image
        run: |
          docker push jordyhenman/henman-wopro-service
