name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK (Java 11, adjust if needed)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Build the Java application
      - name: Build the application
        run: |
          ./mvnw clean package -DskipTests

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t jordyhenman/henman-wopro-service:$GITHUB_SHA .

      # Log in to DockerHub using DockerHub credentials (secrets)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username from secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # DockerHub token from secrets

      # Push the Docker image to DockerHub
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jordyhenman/henman-wopro-service:$GITHUB_SHA
          platform: linux/amd64  # Specify the platform if you're building multi-platform images
